### ISSUE TITLE
Exception trhowing when using  in Windows Phone 8.1 project

### ISSUE THREAD

**Issue by JeanPhilippeKernel** [flagbug/YoutubeExtractor#135] opened 2015-09-06 20:23 UTC
when I use it , in my Windows Phone 8.1 projet, I have an exception : PayementRequired .. don't understand

**Comment by flagbug** [comment] 2015-11-17 14:11
Duplicate of https://github.com/flagbug/YoutubeExtractor/issues/62

**Closed by flagbug** 2015-11-17 14:11 UTC
