### ISSUE TITLE
420p Video Without Sound

### ISSUE THREAD

**Issue by radonband** [flagbug/YoutubeExtractor#171] opened 2016-02-01 22:15 UTC
hi, 
i'm using the latest version and when i download a file with 420 Resolution and VideoType.Mp4, the downloaded file dons't contain any sound.
FYI: all other Resolution downloaded fine. i try more that 100 URL and all of them had this issue.
let me know if you know what is the problems.
thank you.

**Comment by RogerSchmidlin** [comment] 2016-02-29 15:38
I got the same problem. It's not just with 420 Resolution I get it with many others too. Here is one of the links that has video resolutions with no sounds: http://youtube.com/watch?v=ra8Gh_yqlQA

**Comment by flagbug** [comment] 2016-02-29 16:25
Duplicate of https://github.com/flagbug/YoutubeExtractor/issues/78

**Closed by flagbug** 2016-02-29 16:25 UTC
